import { RepertoireInstance, ScoreItem } from '@/types/repertoire';

export const DEMO_INSTANCES: Record<string, RepertoireInstance> = {
  'CANTATE-2026': {
    code: 'CANTATE-2026',
    name: 'Cathedral Chamber Choir',
    subtitle: 'Season 2026 Masterworks & Evensong',
    director: 'Dr. Julian Vance',
    accompanist: 'Elena Rostova (Organ)',
    organization: 'Cathedral Choral Foundation',
    seasonName: '2026 Annual Cycle',
    lastUpdated: '2026-09-12T14:30:00Z',
    setlists: [
      {
        id: 'set-evensong',
        title: 'Choral Evensong & Benediction',
        date: 'Sunday, 5:00 PM',
        description: 'Liturgical service repertoire for Cathedral Nave',
        scoreIds: ['mozart-ave-verum', 'tallis-if-ye-love', 'stanford-beati', 'byrd-ave-verum'],
      },
      {
        id: 'set-gala',
        title: 'Spring Festival Masterworks',
        date: 'Saturday, May 16, 7:30 PM',
        description: 'Full concert program with chamber orchestra',
        scoreIds: ['faure-cantique', 'whitacre-lux', 'palestrina-sicut-cervus', 'victoria-o-magnum'],
      },
    ],
    scores: [
      {
        id: 'mozart-ave-verum',
        title: 'Ave Verum Corpus, K. 618',
        composer: 'Wolfgang Amadeus Mozart',
        arranger: 'Original SATB + Strings',
        lyricist: '14th-century Eucharistic Hymn',
        voicing: 'SATB',
        season: 'Lent',
        keySignature: 'D Major',
        tempo: 'Adagio (♩ = 56)',
        duration: '3:30',
        pageCount: 3,
        sourceUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: 142800,
        downloadStatus: 'idle',
        notes: 'Pianissimo entrance in m. 1. Watch soprano intonation on F natural in m. 22.',
        tags: ['Sacred', 'Motet', 'Eucharist', 'Classical'],
        addedAt: '2026-08-01T10:00:00Z',
      },
      {
        id: 'faure-cantique',
        title: 'Cantique de Jean Racine, Op. 11',
        composer: 'Gabriel Fauré',
        arranger: 'Organ / Piano accompaniment',
        lyricist: 'Jean Racine (tr. from Latin)',
        voicing: 'SATB',
        season: 'General',
        keySignature: 'D♭ Major',
        tempo: 'Andante (♩ = 66)',
        duration: '5:15',
        pageCount: 6,
        sourceUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: 318000,
        downloadStatus: 'idle',
        notes: 'Basses lead at m. 19. Maintain lyrical legato phrasing across all vocal lines.',
        tags: ['French Romantic', 'Sacred', 'Choral Masterwork'],
        addedAt: '2026-08-05T11:00:00Z',
      },
      {
        id: 'palestrina-sicut-cervus',
        title: 'Sicut Cervus',
        composer: 'Giovanni Pierluigi da Palestrina',
        voicing: 'SATB',
        season: 'Lent',
        keySignature: 'F Major (Aet. Mode 2)',
        tempo: 'Moderato espressivo (𝅗 = 60)',
        duration: '3:10',
        pageCount: 4,
        sourceUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: 215400,
        downloadStatus: 'idle',
        notes: 'Strict Renaissance counterpoint. Follow natural word accents; staggered breathing.',
        tags: ['Renaissance', 'Motet', 'Psalm 42', 'Polyphony'],
        addedAt: '2026-08-10T09:15:00Z',
      },
      {
        id: 'victoria-o-magnum',
        title: 'O Magnum Mysterium',
        composer: 'Tomás Luis de Victoria',
        voicing: 'SATB',
        season: 'Christmas',
        keySignature: 'F Dorian (Transposed)',
        tempo: 'Lento misterioso',
        duration: '3:45',
        pageCount: 4,
        sourceUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: 228000,
        downloadStatus: 'idle',
        notes: 'Alleluia section in triple meter (3/2). Clear crisp consonants without clipping tone.',
        tags: ['Renaissance', 'Spanish Polyphony', 'Christmas', 'Motet'],
        addedAt: '2026-08-12T14:00:00Z',
      },
      {
        id: 'tallis-if-ye-love',
        title: 'If Ye Love Me',
        composer: 'Thomas Tallis',
        voicing: 'SATB',
        season: 'Pentecost',
        keySignature: 'F Major',
        tempo: 'Andante con moto',
        duration: '2:15',
        pageCount: 2,
        sourceUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: 112000,
        downloadStatus: 'idle',
        notes: 'Tudor anthem. Second section is repeated. Tenors stay prominent in m. 9.',
        tags: ['Tudor Anthem', 'A Cappella', 'Pentecost', 'Evensong'],
        addedAt: '2026-08-15T16:30:00Z',
      },
      {
        id: 'byrd-ave-verum',
        title: 'Ave Verum Corpus (Gradualia I)',
        composer: 'William Byrd',
        voicing: 'SATB',
        season: 'Lent',
        keySignature: 'G Minor',
        tempo: 'Adagio doloroso',
        duration: '4:10',
        pageCount: 4,
        sourceUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: 245000,
        downloadStatus: 'idle',
        notes: 'Cross-relations between F# and F natural. Emphasize "Miserere mei" climax.',
        tags: ['Tudor', 'Recusant Polyphony', 'Sacred', 'Lent'],
        addedAt: '2026-08-18T08:00:00Z',
      },
      {
        id: 'whitacre-lux',
        title: 'Lux Aurumque',
        composer: 'Eric Whitacre',
        lyricist: 'Edward Esch (tr. Charles Anthony Silvestri)',
        voicing: 'SATB div.',
        season: 'Concert',
        keySignature: 'C# Minor',
        tempo: 'Adagio molto legato',
        duration: '4:20',
        pageCount: 5,
        sourceUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: 340000,
        downloadStatus: 'idle',
        notes: 'Cluster chords need zero vibrato. Warm luminous sound on final "natum".',
        tags: ['Contemporary', 'Choral Clusters', 'Concert', 'Atmospheric'],
        addedAt: '2026-08-20T12:00:00Z',
      },
      {
        id: 'stanford-beati',
        title: 'Beati Quorum Via, Op. 38 No. 3',
        composer: 'Charles Villiers Stanford',
        voicing: 'SSAA',
        season: 'Evensong',
        keySignature: 'A♭ Major',
        tempo: 'Andante tranquillo',
        duration: '3:35',
        pageCount: 5,
        sourceUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: 280000,
        downloadStatus: 'idle',
        notes: 'Six-part texture. Floating seamless lines. Upper sopranos maintain floating high G.',
        tags: ['Victorian', 'Anglican Anthem', 'Psalm 119', 'Six-part'],
        addedAt: '2026-08-22T10:00:00Z',
      },
    ],
  },

  'CHORALE-LENT': {
    code: 'CHORALE-LENT',
    name: 'St. Cecilia Chorale',
    subtitle: 'Lent, Holy Week & Tenebrae',
    director: 'Maestro Marcus Thorne',
    accompanist: 'A Cappella Project',
    organization: 'St. Cecilia Music Society',
    seasonName: 'Passiontide 2026',
    lastUpdated: '2026-09-14T08:00:00Z',
    setlists: [
      {
        id: 'set-tenebrae',
        title: 'Service of Tenebrae (Good Friday)',
        date: 'Good Friday, 8:00 PM',
        description: 'Solemn candlelight service without accompaniment',
        scoreIds: ['allegri-miserere', 'lotti-crucifixus', 'purcell-thou-knowest'],
      },
    ],
    scores: [
      {
        id: 'allegri-miserere',
        title: 'Miserere Mei, Deus',
        composer: 'Gregorio Allegri',
        voicing: 'SATB div.',
        season: 'Holy Week',
        keySignature: 'G Minor',
        tempo: 'Adagio semplice',
        duration: '12:00',
        pageCount: 8,
        sourceUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: 450000,
        downloadStatus: 'idle',
        notes: 'Solo quartet stationed in gallery. High C soprano: pure, ethereal tone.',
        tags: ['Sistine Chapel', 'Holy Week', 'Falsobordone', 'High C'],
        addedAt: '2026-08-01T10:00:00Z',
      },
      {
        id: 'lotti-crucifixus',
        title: 'Crucifixus a 8',
        composer: 'Antonio Lotti',
        voicing: 'TTBB',
        season: 'Holy Week',
        keySignature: 'D Minor',
        tempo: 'Grave',
        duration: '3:20',
        pageCount: 4,
        sourceUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: 240000,
        downloadStatus: 'idle',
        notes: '8-part overlapping suspensions. Intense crescendo through dissonances.',
        tags: ['Baroque', 'Venetian', 'Suspensions', 'Holy Week'],
        addedAt: '2026-08-03T11:00:00Z',
      },
      {
        id: 'purcell-thou-knowest',
        title: 'Thou Knowest, Lord, the Secrets of our Hearts',
        composer: 'Henry Purcell',
        voicing: 'SATB',
        season: 'Lent',
        keySignature: 'E♭ Major',
        tempo: 'Largo con solennità',
        duration: '2:40',
        pageCount: 2,
        sourceUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: 135000,
        downloadStatus: 'idle',
        notes: 'From the Funeral Music for Queen Mary. Homophonic solemnity.',
        tags: ['English Baroque', 'Funeral Sentences', 'Solemn'],
        addedAt: '2026-08-07T14:00:00Z',
      },
    ],
  },

  'VOICES-SPRING': {
    code: 'VOICES-SPRING',
    name: 'Vox Chamber Ensemble',
    subtitle: 'Spring Madrigals & Partsongs',
    director: 'Claire Henderson',
    seasonName: 'Spring Tour 2026',
    lastUpdated: '2026-09-10T12:00:00Z',
    setlists: [
      {
        id: 'set-madrigals',
        title: 'Maytime Madrigal Gala',
        date: 'Saturday, May 2, 7:00 PM',
        description: 'English and French Renaissance secular works',
        scoreIds: ['morley-month-of-maying', 'gibbons-silver-swan'],
      },
    ],
    scores: [
      {
        id: 'morley-month-of-maying',
        title: 'Now Is the Month of Maying',
        composer: 'Thomas Morley',
        voicing: 'SAB',
        season: 'Concert',
        keySignature: 'G Major',
        tempo: 'Allegro vivace (♩ = 120)',
        duration: '1:50',
        pageCount: 2,
        sourceUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: 120000,
        downloadStatus: 'idle',
        notes: 'Fa-la-la refrains should be lively, detached, and spirited.',
        tags: ['English Madrigal', 'Ballett', 'Spring', 'Secular'],
        addedAt: '2026-08-01T10:00:00Z',
      },
      {
        id: 'gibbons-silver-swan',
        title: 'The Silver Swan',
        composer: 'Orlando Gibbons',
        voicing: 'SATB',
        season: 'Concert',
        keySignature: 'F Major',
        tempo: 'Andantino mesto',
        duration: '1:45',
        pageCount: 2,
        sourceUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: 118000,
        downloadStatus: 'idle',
        notes: '"More geese than swans now live, more fools than wise." Subtle dynamic nuances.',
        tags: ['English Madrigal', 'Jacobean', 'Secular'],
        addedAt: '2026-08-04T12:00:00Z',
      },
    ],
  },
};

export class InstanceService {
  /**
   * Validate and retrieve choir repertoire instance by code
   */
  static async fetchInstance(rawCode: string): Promise<RepertoireInstance | null> {
    const normalizedCode = rawCode.trim().toUpperCase();
    if (DEMO_INSTANCES[normalizedCode]) {
      // Return a deep clone to avoid mutating static data
      return JSON.parse(JSON.stringify(DEMO_INSTANCES[normalizedCode]));
    }

    // If code format is valid (e.g. CHOIR-1234) but not in demo, synthesize a new empty/starter choir instance
    if (/^[A-Z0-9]{3,8}-[A-Z0-9]{2,6}$/.test(normalizedCode)) {
      return {
        code: normalizedCode,
        name: `Repertoire Instance [${normalizedCode}]`,
        subtitle: 'Choir Repertoire Cloud Repository',
        director: 'Choir Director',
        seasonName: 'Current Rehearsal Cycle',
        scores: [],
        setlists: [],
        lastUpdated: new Date().toISOString(),
      };
    }

    return null;
  }

  /**
   * List available demo instances for quick testing
   */
  static getAvailableDemoInstances(): Array<{ code: string; name: string; scoreCount: number }> {
    return Object.values(DEMO_INSTANCES).map(instance => ({
      code: instance.code,
      name: instance.name,
      scoreCount: instance.scores.length,
    }));
  }
}
